### ISSUE TITLE
Class 'Utils\Helper' not found

### ISSUE THREAD

**Issue by adozhao** [whitebearcode/typecho-beardocs#2]
应用主题后进入前台报错：  

`
Class 'Utils\Helper' not found
`

**Comment by whitebearcode** [comment]
你好，请确认为Typecho v1.2.1最新版本
https://github.com/typecho/typecho/releases/latest/download/typecho.zip

**Comment by adozhao** [comment]
感谢指点，已正常运行，谢谢🌹
