### ISSUE TITLE
设置外观样式缺失

### ISSUE THREAD

**Issue by adozhao** [whitebearcode/typecho-beardocs#3]
![image](https://github.com/user-attachments/assets/d1d89b95-4d62-4337-87bc-72aaad642f7e)

**Comment by whitebearcode** [comment]
这个问题需检查目录权限是否给全

**Comment by adozhao** [comment]
刚更改为777，但是好像还是不行~

**Comment by whitebearcode** [comment]
在/usr/plugins目录重新覆盖一下最新版本的BearDocsCore

**Comment by adozhao** [comment]
> 在/usr/plugins目录重新覆盖一下最新版本的BearDocsCore  
重新覆盖了下，好像还是不行~
![image](https://github.com/user-attachments/assets/eceee8b7-8943-4d76-a7ee-a4ae1c6800a2)

**Comment by whitebearcode** [comment]
这个问题第一次遇到
可以尝试下
1、暂时先禁用除了BearDocsCore外的所有插件
2、看图权限组与其他插件不一致，设置成与其他插件一致试试

**Comment by whitebearcode** [comment]
你好，若问题还未解决，可加QQ交流群咨询。

**Comment by adozhao** [comment]
路径问题，多了两个层级，我这边是docker部署的，用的如下镜像：  
`image: 80x86/typecho:v1.2.1-rc.2-amd64`  
@whitebearcode 

![image](https://github.com/user-attachments/assets/2b79aea7-1120-44f0-b7c0-23a7faebe780)

**Comment by adozhao** [comment]
我按照如下目录放置就行了，但是这个问题的根本原因还不知道是为啥 ，可能你代码里的路径拼接逻辑有问题~

![image](https://github.com/user-attachments/assets/57738457-aa02-4830-9a43-d54d319767c9)

**Comment by whitebearcode** [comment]
好的，晚点我看一下，感谢反馈
