### ISSUE TITLE
搜索一直失败

### ISSUE THREAD

**Issue by adozhao** [whitebearcode/typecho-beardocs#5]
![image](https://github.com/user-attachments/assets/f7674f30-d090-4b77-9417-8c958de39fd8)

**Comment by whitebearcode** [comment]
请问这个问题解决了吗

**Comment by adozhao** [comment]
还没有，您可以看一下，[点击这里](http://212.129.221.55:9468/)

**Comment by whitebearcode** [comment]
看到你的问题了，可以试试换成域名访问

**Comment by adozhao** [comment]
> 看到你的问题了，可以试试换成域名访问

换成域名好像还是不行，[点此再次查看](https://blog.rmb.life/)

**Comment by whitebearcode** [comment]
后台所设置域名是否和所访问域名一致
后台域名设置位于设置-基本中，非设置外观

**Comment by adozhao** [comment]
木有对应设置项，`控制台-个人设置`中倒是有个人主页选项，和实际地址是一致的

![image](https://github.com/user-attachments/assets/5265146c-c6e3-4220-9206-62507c79a28c)

**Comment by whitebearcode** [comment]
好的，知道问题了，正常版本基本设置中是有站点地址项的
这个问题下个版本修复，感谢反馈

**Comment by whitebearcode** [comment]
v1.0.7版本已发布
你可能需要进行覆盖升级
因为你是容器部署，兼容在最新版本中得到处理
https://github.com/whitebearcode/typecho-beardocs/releases/tag/v1.0.7

**Comment by adozhao** [comment]
新版本测试OK @whitebearcode
