### ISSUE TITLE
子分类的图标显示默认的“设置”图标

### ISSUE THREAD

**Issue by adozhao** [whitebearcode/typecho-beardocs#6]
子分类的图标目前为默认的图标，建议改为父类的图标也行~

**Comment by whitebearcode** [comment]
收到建议，感谢反馈

**Comment by adozhao** [comment]
新版本开启相应功能后子类图标是继承父类图标了，但是父类图标变为默认的“设置”图标了 @whitebearcode

**Comment by whitebearcode** [comment]
你好，我在测试中并没有发现此问题
不过我改进了其逻辑并修复了一些已知BUG
已发布新版本，你可以升级并测试
https://github.com/whitebearcode/typecho-beardocs/releases/tag/v1.0.8

**Comment by adozhao** [comment]
@whitebearcode   已升级到最新版本，问题依然存在

![image](https://github.com/user-attachments/assets/1e6eab67-9072-43af-a6bd-6fa8c696530d)

**Comment by whitebearcode** [comment]
你好，v1.0.9版本已推出，你可升级至v1.0.9版本再进行测试
https://github.com/whitebearcode/typecho-beardocs/releases/tag/v1.0.9
这个版本中应该已经修复了此问题:)

**Comment by adozhao** [comment]
1.0.9问题依然存在~

**Comment by whitebearcode** [comment]
看着应该是部分环境下无法正常获取的问题
演示站是没有这个问题的～
https://beardocs.typecho.ru

若要进一步处理这个问题，可能需要你提供Typecho站点测试账户，信息可发送至whitebear@msn.com
我会继续排查问题所在:)

**Comment by adozhao** [comment]
已发

**Comment by whitebearcode** [comment]
可能需要给予usr目录可写权限，方便调试:)

**Comment by adozhao** [comment]
> 可能需要给予usr目录可写权限，方便调试:)

全部是777了

**Comment by adozhao** [comment]
很奇怪，为嘛你的没问题，我们的区别应该只是部署方式不一样。而且我发现，我这个没办法在线更新，进度条一直是0，可能也是容器部署导致的

**Comment by whitebearcode** [comment]
已重新处理识别逻辑，现在你的没问题了

**Comment by whitebearcode** [comment]
> 很奇怪，既然你的没问题，我们的区别应该只是部署方式不一样。而且我发现，我这个没办法在线更新，进度条一直是0，可能也是容器部署导致的

无法在线升级是因为你权限没有赋予，现在在线升级应该也没问题了

**Comment by adozhao** [comment]
非常感谢，您辛苦了🌹
