### ISSUE TITLE
启用主题后无法进入页面

### ISSUE THREAD

**Issue by 56warmers** [whitebearcode/typecho-beardocs#7]
docker部署，外置mysql数据库，版本1.3.0
上传插件、主题后，保存主题文件一次，启用主题
启用主题后无法进入页面，空白

**Comment by whitebearcode** [comment]
暂不支持typecho 1.3
仅兼容到typecho 1.2.1
待1.3正式版推出就会进行适配兼容:)

**Comment by 56warmers** [comment]
> 暂不支持typecho 1.3 仅兼容到typecho 1.2.1 待1.3正式版推出就会进行适配兼容:)

好的，感谢回复，非常喜欢你的主题。
我会切回1.2.1试试
